import Web from "../../public/svgs/options/Web.svg";
import Academic from "../../public/svgs/options/Academic.svg";
import Writing from "../../public/svgs/options/Writing.svg";
// import Youtube from "../../public/svgs/options/Youtube.svg";
// import Reddit from "../../public/svgs/options/Reddit.svg";
// import Stackoverflow from "../../public/svgs/options/Stackoverflow.svg";

export const focusOptions = [
  {website: "Model", query: "", description: "默认"},
  {website: "claude-3-5-haiku-20241022", query: "", description: "轻量级Claude 3.5,适合快速对话和简单任务"},
  {website: "claude-3-5-sonnet-20240620", query: "", description: "Claude 3.5中等版本,平衡性能和资源消耗"},
  {website: "claude-3-5-sonnet-20241022", query: "", description: "更新版Claude 3.5,增强了上下文理解能力"},
  {website: "claude-3-7-sonnet-20250219", query: "", description: "最新Claude 3.7,具有更强的推理和创造能力"},
  {website: "claude-3-7-sonnet-20250219-thinking", query: "", description: "思考型Claude 3.7,专注于深度分析和复杂问题解决"},
  {website: "claude-3-opus-20240229", query: "", description: "高级版Claude 3,支持更长对话和复杂任务处理"},
  {website: "deepseek-chat", query: "", description: "Deepseek对话模型,擅长自然语言交互"},
  {website: "deepseek-r1", query: "", description: "Deepseek研究型模型,适合学术和专业领域"},
  {website: "deepseek-reasoner", query: "", description: "Deepseek推理模型,专注于逻辑分析和问题解决"},
  {website: "deepseek-v3", query: "", description: "Deepseek第三代模型,全面提升性能和能力"},
  {website: "doubao-1-5-lite-32k", query: "", description: "豆包1.5轻量版,支持32K上下文"},
  {website: "doubao-1-5-lite-32k-250115", query: "", description: "更新版豆包1.5轻量版,优化性能"},
  {website: "doubao-1-5-pro-256k-250115", query: "", description: "豆包1.5专业版,支持256K超长上下文"},
  {website: "doubao-1-5-pro-32k-250115", query: "", description: "豆包1.5专业版,32K上下文优化版本"},
  {website: "doubao-1-5-vision-pro-32k", query: "", description: "豆包1.5视觉专业版,支持图像理解"},
  {website: "doubao-1.5-pro-256k", query: "", description: "豆包1.5专业版,支持超长对话"},
  {website: "gemini-1.5-flash", query: "", description: "Gemini 1.5闪电版,快速响应且高效"},
  {website: "gemini-1.5-flash-002", query: "", description: "Gemini 1.5闪电版更新版本,性能优化"},
  {website: "gemini-1.5-flash-8b", query: "", description: "Gemini 1.5闪电版轻量模型,8B参数"},
  {website: "gemini-1.5-flash-exp-0827", query: "", description: "Gemini 1.5闪电版实验性版本"},
  {website: "gemini-1.5-flash-latest", query: "", description: "Gemini 1.5闪电版最新版本,持续优化"},
  {website: "gemini-1.5-pro", query: "", description: "Gemini 1.5专业版,全面的AI能力"},
  {website: "gemini-1.5-pro-002", query: "", description: "Gemini 1.5专业版更新版本"},
  {website: "gemini-1.5-pro-exp-0801", query: "", description: "Gemini 1.5专业版实验性版本"},
  {website: "gemini-1.5-pro-latest", query: "", description: "Gemini 1.5专业版最新版本,全面升级"},
  {website: "gemini-2.0-flash", query: "", description: "Gemini 2.0闪电版,新一代快速响应模型"},
  {website: "gemini-2.0-flash-001", query: "", description: "Gemini 2.0闪电版首个更新版本"},
  {website: "gemini-2.0-flash-exp", query: "", description: "Gemini 2.0闪电版实验性功能版本"},
  {website: "gemini-2.0-flash-lite", query: "", description: "Gemini 2.0闪电版轻量版,平衡性能和资源"},
  {website: "gemini-2.0-flash-lite-preview-02-05", query: "", description: "Gemini 2.0闪电版轻量预览版"},
  {website: "gemini-2.0-flash-thinking-exp", query: "", description: "Gemini 2.0闪电版思考型实验版本"},
  {website: "gemini-2.0-flash-thinking-exp-1219", query: "", description: "Gemini 2.0闪电版思考能力增强版"},
  {website: "gemini-2.0-pro-exp-02-05", query: "", description: "Gemini 2.0专业版实验性版本"},
  {website: "gpt-3.5-turbo", query: "", description: "GPT-3.5 Turbo版本,快速且经济实惠"},
  {website: "gpt-3.5-turbo-0125", query: "", description: "GPT-3.5 Turbo更新版本,优化性能"},
  {website: "gpt-3.5-turbo-0301", query: "", description: "GPT-3.5 Turbo 3月版本,稳定可靠"},
  {website: "gpt-3.5-turbo-0613", query: "", description: "GPT-3.5 Turbo 6月版本,功能增强"},
  {website: "gpt-3.5-turbo-1106", query: "", description: "GPT-3.5 Turbo 11月版本,全面升级"},
  {website: "gpt-3.5-turbo-16k", query: "", description: "GPT-3.5 Turbo 16K上下文版本"},
  {website: "gpt-3.5-turbo-16k-0613", query: "", description: "GPT-3.5 Turbo 16K 6月优化版"},
  {website: "gpt-4", query: "", description: "GPT-4基础版,强大的通用AI能力"},
  {website: "gpt-4-0125-preview", query: "", description: "GPT-4预览版,尝鲜新功能"},
  {website: "gpt-4-0314", query: "", description: "GPT-4 3月版本,性能稳定"},
  {website: "gpt-4-0613", query: "", description: "GPT-4 6月版本,优化升级"},
  {website: "gpt-4-1106-preview", query: "", description: "GPT-4 11月预览版,新特性体验"},
  {website: "gpt-4-32k", query: "", description: "GPT-4 32K上下文版本,支持更长对话"},
  {website: "gpt-4-32k-0314", query: "", description: "GPT-4 32K 3月版本"},
  {website: "gpt-4-32k-0613", query: "", description: "GPT-4 32K 6月优化版"},
  {website: "gpt-4-turbo", query: "", description: "GPT-4 Turbo版本,更快响应速度"},
  {website: "gpt-4-turbo-2024-04-09", query: "", description: "GPT-4 Turbo 2024年4月版本"},
  {website: "gpt-4-turbo-preview", query: "", description: "GPT-4 Turbo预览版,抢先体验"},
  {website: "gpt-4-vision-preview", query: "", description: "GPT-4视觉预览版,支持图像理解"},
  {website: "gpt-4.5-preview", query: "", description: "GPT-4.5预览版,新一代模型预览"},
  {website: "gpt-4.5-preview-2025-02-27", query: "", description: "GPT-4.5 2025年2月预览版"},
  {website: "gpt-4o", query: "", description: "GPT-4优化版,全面性能提升"},
  {website: "gpt-4o-2024-05-13", query: "", description: "GPT-4优化版2024年5月版本"},
  {website: "gpt-4o-2024-08-06", query: "", description: "GPT-4优化版2024年8月版本"},
  {website: "gpt-4o-2024-11-20", query: "", description: "GPT-4优化版2024年11月版本"},
  {website: "gpt-4o-mini", query: "", description: "GPT-4优化版轻量版,平衡性能"},
  {website: "gpt-4o-mini-2024-07-18", query: "", description: "GPT-4优化版轻量版7月更新"},
  {website: "grok-3", query: "", description: "Grok 3基础版,创新的对话体验"},
  {website: "grok-3-r1", query: "", description: "Grok 3 R1版本,研究增强型"},
  {website: "grok-3-reason", query: "", description: "Grok 3推理版,强化逻辑分析"},
  {website: "o1", query: "", description: "O1基础版,高效智能助手"},
  {website: "o1-2024-12-17", query: "", description: "O1 2024年12月更新版本"},
  {website: "o1-mini", query: "", description: "O1轻量版,快速响应"},
  {website: "o1-mini-2024-09-12", query: "", description: "O1轻量版2024年9月版本"},
  {website: "o1-preview", query: "", description: "O1预览版,新功能抢先体验"},
  {website: "o1-preview-2024-09-12", query: "", description: "O1预览版2024年9月版本"},
  {website: "o3-mini", query: "", description: "O3轻量版,新一代轻量模型"},
  {website: "o3-mini-2025-01-31", query: "", description: "O3轻量版2025年1月版本"},
  {website: "qvq-72b-preview", query: "", description: "QVQ 72B预览版,大规模参数模型"},
  {website: "qwen-max-2025-01-25", query: "", description: "通义千问Max版2025年1月版本"},
  {website: "qwen-max-latest", query: "", description: "通义千问Max最新版本"},
  {website: "qwen-omni-turbo", query: "", description: "通义千问全能加速版"},
  {website: "qwen-omni-turbo-latest", query: "", description: "通义千问全能加速最新版"},
  {website: "qwen-plus-latest", query: "", description: "通义千问Plus最新版本"},
  {website: "qwen-turbo-1101", query: "", description: "通义千问加速版11月版本"},
];



export const PLUGINS = [
  {
    tag: "Built In",
    name: "Stocks",
    comingSoon: false,
    url: "/plugins/stocks",
    description: "Check stock prices",
  },
  {
    tag: "Built In",
    name: "Weather",
    comingSoon: false,
    url: "/plugins/weather",
    description: "Weather forecast",
  },
  {
    tag: "Built In",
    name: "Dictionary",
    comingSoon: false,
    url: "/plugins/dictionary",
    description: "Look up word definitions",
  },
];